### ISSUE TITLE
Fluctuating and Erratic curves don't work past L100.

### ISSUE THREAD

**Issue by luckytyphlosion** [Skeli789/Complete-Fire-Red-Upgrade#1]
### Fluctuating
Fluctuating requires way too much experience compared to the rest of the curves. For example, at level 200, Fluctuating has a total of 21120000 experience points, while the next largest curve (Slow), only has a total of 10000000 experience points, which is less than half of Fluctuating's required experience.
### Erratic
You have realized that total experience would become negative if the level cap is greater than 160, so you chose to use the formula: [(level^3 * (maxLevel + 60 - level))/100](https://github.com/Skeli789/Complete-Fire-Red-Upgrade/blob/master/src/exp.c#L641-L645). This has two major issues.

The first is there will be a sudden discontinuity between the total experience of level 100 and total experience of level 101, since levels 98-100 would still use the computed lookup tables.

The second and more important issue is that this does not account for **marginal experience** (experience to the next level). For a max level of 180 and beyond, the maximum experience would actually **start to decrease** beyond a certain level, which means that a Pokémon would require **negative** experience to level up.

Even for a max level below 180, Erratic would require pitifully low amounts of experience to level up. Beyond an early point between L100 and the max level (dependent on when f'(x) = 0), the formula will start to require decreasing amounts of experience. While this behaviour is somewhat similar to Erratic's experience requirements to the next level, it produces extreme behaviour compared to other curves. With a max level of 150, Erratic would only need 7152 experience points to level up to level 150, while a formula like Fast requires 42841 experience points, which is almost 6 times more!

At levels closer to 180, you would have extremely low experience requirements. With a max level of 175, Erratic would require less than 1/27th of the experience that Fast would require to level from 174 to 175 (2131 vs. 58381). Of course, you could try to plan around this by setting the max level to something far higher than what the expected level would be at whatever final postgame boss there is, but at that point you may as well re-evaluate the entire experience curve.

## From a design standpoint
Looks are deceiving, but the total experience of Fluctuating and Erratic do not tell us the full story of their purpose.

The design behind the Fluctuating curve is that the early levels require low amounts of experience to level up, while the later levels require much more experience to level up. The inverse is the same for Erratic; the early levels require high amounts of experience to level up, while the later levels require much less experience. Actual numbers aren't really important here, you can look at [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Experience#Experience_at_each_level) for that, but the point is to understand the idea.

With this knowledge, the correct way to create the Fluctuating and Erratic curves would be to stretch its behaviour across the entire level curve (rather than just extrapolating its behaviour from the last defined function) although I haven't tried attempting this myself, and it would likely require a bit of testing in-game to see how it works out.

One final thing: I haven't checked, but I also wouldn't be surprised if there was any overflow calculating experience for levels past 100.

**Comment by Skeli789** [comment]
Thanks for your input! When I increased the potential max level, I didn't really put much effort into designing a new curve. I just tried fixing it to make sure it wouldn't crash, and then I moved on. I personally didn't have the intention of making use of the feature, but I'll see what I can do to design new curves.

**Comment by Skeli789** [comment]
The exp curves have now been updated to reflect what DizzyEgg used here https://github.com/DizzyEggg/Various-EM-features/blob/master/src/MoreLevels.c.
