### ISSUE TITLE
dev branch bag issue

### ISSUE THREAD

**Issue by Yave-Yu** [Skeli789/Complete-Fire-Red-Upgrade#113]
If button mode set to HELP or LR, bag couldn't switch page, however L=A works fine.

**Comment by adamg88** [comment]
Can confirm the same, it got broken in the following [commit](https://github.com/Skeli789/Complete-Fire-Red-Upgrade/commit/388fa8461d9beb04c8fe357fcf96cbf926c11138).

**Comment by Skeli789** [comment]
Yeah LR is fast scroll instead because the bag can tend to get quite full. You can just revert that commit @adamg88 linked and it will probably solve the issue.
