### ISSUE TITLE
Ability pop-up freezing the game

### ISSUE THREAD

**Issue by kimwnasptd** [Skeli789/Complete-Fire-Red-Upgrade#116]
**The problem**
When an ability pop-up is about to appear, the game completly freezes.
![Screenshot 2023-08-13 164210](https://github.com/Skeli789/Complete-Fire-Red-Upgrade/assets/11134742/350f63b5-5cd9-4526-9ff5-1542c5bbd714)

**Reproduce**
I'm attaching a `.sav` file, in which there's a pikachu in the team. Use it in a battle and let the other pokemon do physical attack, until Picachu's effect will trigger.

[test.sav.zip](https://github.com/Skeli789/Complete-Fire-Red-Upgrade/files/12330695/test.sav.zip)

**Environment**
* Used commit ca188c03a4640cc5c8d06c9c9a057cb8cb1e936f (from `master`) 
* Applied this patch on top of 1.0 Squirrels ROM
* Same happens if I first apply the https://github.com/Skeli789/Dynamic-Pokemon-Expansion patch first

---

Is something completely wrong with my setup? Any chances there's a quick fix for this?

**Comment by Skeli789** [comment]
Please download the version of devkitPro linked in the **Note** of Step 1 here: https://github.com/Skeli789/Complete-Fire-Red-Upgrade/wiki/Windows-Installation-Instructions
