### ISSUE TITLE
Error Compìling

### ISSUE THREAD

**Issue by Jko2** [Skeli789/Complete-Fire-Red-Upgrade#12]
Assembling ./assembly\main.s
Error! The assembler could not be located.
Are you sure you set up your path to devkitPro/devkitARM/bin correctly?
Inserting code.
Error: The insertion process could not be completed.
The linker symbol file was not found.
PS C:\cda>

**Comment by Skeli789** [comment]
It seems your assembler is missing. Did you fully complete step 1 in the readme under installation instructions?

**Comment by Jko2** [comment]
Yes, I have installed everything necessary to compile but I still see error

**Comment by splatoonkapptain05** [comment]
Hello!
Sorry if this is late, but I'm also running into similar issues of compiling.
I've followed steps 1 to 5 to the best of my abilities and currently struggling
with step 6. When I tried to open to open the make.py in the 'scripts' folder
it closes immediately. Sometimes, it flashes an error of some sort but it's too quick for me
to process it. So the next thing I did was force open make.py in cmd to see what the possible error it was.
It came up with the following message:

Error: Could not find source rom: "BPRE0.gba".
Please make sure a rom with this name exists in the root.

I decided then to skip to the step where we 'make' the test.gba and offsets.ini and lo and behold, it's the same error that the author mentioned in the opening statement, missing assembler and all.

The thing is, I have the clean 'BPRE0.gba' rom in the master folder.
Both system variable paths for 'devkitARMbin' and Dep files are currently set as
the last two addressess below all of the other directories:(I have a hunch that I misunderstood this part)

They are written as:

;C:\devkitPro\devkitARM\bin\
;C:\Users\'username'\Desktop\PkmTB\deps

I know this is more of a human error rather than a compiling one since people have got it working before and after me. I'm wondering where have I went wrong
I've been working to get this working for the past two days and figured it wouldn't be very good for me to keep all of this pent-up frustration to myself.

**Comment by Skeli789** [comment]
You need to open the command line from the root and then run the make script. Running the make script from the scripts folder won’t do anything. The current directory needs to be set to the root.

**Comment by splatoonkapptain05** [comment]
So I've decided to reinstall python, devkitArm and re-extract the file (thank goodness for backups!)
and I realized that there is something there that I haven't seen before. After I extracted the upgrade, the directory just before accessing the master folder, there is an extra make.py script.
![The extra make py in question](https://user-images.githubusercontent.com/54601050/64070349-93a43280-cc12-11e9-85fc-0199fa026768.PNG)
 It appears that there is a modified time difference of 54 minutes between this .py file and the newly extracted file I haven't done anything else to the file other
than moving the deps to the root (In this case, C:\) and adding the BPRE0 again to the master folder. The other make.py file is still in the scripts folder. Is this suppose to happen?
 I've built simple games before in the past, but never had any experiences compiling and making ROM hacks so this process is very new to me.

**Comment by splatoonkapptain05** [comment]
Never mind. I figured it out, and it assembled properly! I guess that extra python file was (properly not) necessary. Thanks for the help Skeli! Good luck on your final stretch of finishing your ROM hack! It looks great so far and I look forward to what it has in store! :D

**Comment by splatoonkapptain05** [comment]
Ultimately, I decided to leave that extra script alone and went to the master file to compile. It successfully assembled, compiled, build, the file... only for it to reach an error in the Traceback section and failed to inject.

  FileNotFoundError: [WinError 2] The system cannot find the file specified
  Inserting code.
  C:\devkitPro\devkitARM\bin\arm-none-eabi-objdump: 'build/linked.o': No such file
  Error: The insertion process could not be completed.
  The linker symbol file was not found.

Where should I go from here?

**Comment by Raduziel** [comment]
Hi,

I've followed steps 4-6 inside step #1 from this Readme.

Yet I can't assemble. As you can see, the environment patch was designed:

![1](https://user-images.githubusercontent.com/30203065/91678374-c7fb4900-eb1b-11ea-9791-732613127ef0.PNG)

![2](https://user-images.githubusercontent.com/30203065/91678375-c92c7600-eb1b-11ea-9f8d-bf22482fc401.PNG)

I'm using Python 3.7.9 (the tutorial says to use the latest version of 3.7... that is now .9)

The DevKitArm folder is properly pointed:

![3](https://user-images.githubusercontent.com/30203065/91678511-288a8600-eb1c-11ea-9ce2-96fb46d169f8.PNG)

![4](https://user-images.githubusercontent.com/30203065/91678512-29231c80-eb1c-11ea-930f-2645081dfc31.PNG)

Can you please help a nostalgic nerd to play this awesome game the way it should have been released?

Thanks in advance!

**Comment by PyerreIA12** [comment]
> Hi,
> 
> I've followed steps 4-6 inside step #1 from this Readme.
> 
> Yet I can't assemble. As you can see, the environment patch was designed:
> 
> ![1](https://user-images.githubusercontent.com/30203065/91678374-c7fb4900-eb1b-11ea-9791-732613127ef0.PNG)
> 
> ![2](https://user-images.githubusercontent.com/30203065/91678375-c92c7600-eb1b-11ea-9f8d-bf22482fc401.PNG)
> 
> I'm using Python 3.7.9 (the tutorial says to use the latest version of 3.7... that is now .9)
> 
> The DevKitArm folder is properly pointed:
> 
> ![3](https://user-images.githubusercontent.com/30203065/91678511-288a8600-eb1c-11ea-9ce2-96fb46d169f8.PNG)
> 
> ![4](https://user-images.githubusercontent.com/30203065/91678512-29231c80-eb1c-11ea-930f-2645081dfc31.PNG)
> 
> Can you please help a nostalgic nerd to play this awesome game the way it should have been released?
> 
> Thanks in advance!

vc conseguiu?

**Comment by PyerreIA12** [comment]
> Hi,
> 
> I've followed steps 4-6 inside step #1 from this Readme.
> 
> Yet I can't assemble. As you can see, the environment patch was designed:
> 
> ![1](https://user-images.githubusercontent.com/30203065/91678374-c7fb4900-eb1b-11ea-9791-732613127ef0.PNG)
> 
> ![2](https://user-images.githubusercontent.com/30203065/91678375-c92c7600-eb1b-11ea-9f8d-bf22482fc401.PNG)
> 
> I'm using Python 3.7.9 (the tutorial says to use the latest version of 3.7... that is now .9)
> 
> The DevKitArm folder is properly pointed:
> 
> ![3](https://user-images.githubusercontent.com/30203065/91678511-288a8600-eb1c-11ea-9ce2-96fb46d169f8.PNG)
> 
> ![4](https://user-images.githubusercontent.com/30203065/91678512-29231c80-eb1c-11ea-930f-2645081dfc31.PNG)
> 
> Can you please help a nostalgic nerd to play this awesome game the way it should have been released?
> 
> Thanks in advance!

vc conseguiu?

**Comment by Raduziel** [comment]
> > Hi,
> > I've followed steps 4-6 inside step #1 from this Readme.
> > Yet I can't assemble. As you can see, the environment patch was designed:
> > ![1](https://user-images.githubusercontent.com/30203065/91678374-c7fb4900-eb1b-11ea-9791-732613127ef0.PNG)
> > ![2](https://user-images.githubusercontent.com/30203065/91678375-c92c7600-eb1b-11ea-9f8d-bf22482fc401.PNG)
> > I'm using Python 3.7.9 (the tutorial says to use the latest version of 3.7... that is now .9)
> > The DevKitArm folder is properly pointed:
> > ![3](https://user-images.githubusercontent.com/30203065/91678511-288a8600-eb1c-11ea-9ce2-96fb46d169f8.PNG)
> > ![4](https://user-images.githubusercontent.com/30203065/91678512-29231c80-eb1c-11ea-930f-2645081dfc31.PNG)
> > Can you please help a nostalgic nerd to play this awesome game the way it should have been released?
> > Thanks in advance!
> 
> vc conseguiu?

Yup, it was a matter of rearranging the order of the environment variables to look like this:

![Capturar](https://user-images.githubusercontent.com/30203065/92946237-c4759500-f42c-11ea-946c-336cbf5f9784.PNG)

**Comment by LOuroboros** [comment]
> 
> 
> Hi,
> 
> I've followed steps 4-6 inside step #1 from this Readme.
> 
> Yet I can't assemble. As you can see, the environment patch was designed:
> 
> ![1](https://user-images.githubusercontent.com/30203065/91678374-c7fb4900-eb1b-11ea-9791-732613127ef0.PNG)
> 
> ![2](https://user-images.githubusercontent.com/30203065/91678375-c92c7600-eb1b-11ea-9f8d-bf22482fc401.PNG)
> 
> I'm using Python 3.7.9 (the tutorial says to use the latest version of 3.7... that is now .9)
> 
> The DevKitArm folder is properly pointed:
> 
> ![3](https://user-images.githubusercontent.com/30203065/91678511-288a8600-eb1c-11ea-9ce2-96fb46d169f8.PNG)
> 
> ![4](https://user-images.githubusercontent.com/30203065/91678512-29231c80-eb1c-11ea-930f-2645081dfc31.PNG)
> 
> Can you please help a nostalgic nerd to play this awesome game the way it should have been released?
> 
> Thanks in advance!

I know it's been some time since you wrote this post, @Raduziel, but I wanted to clarify that the way you set the path to devkitARM inside the PATH variable was mostly correct. The problem is that semicolon at the beginning of the path which shouldn't have been there.
Without it, chances are things would have worked like that too.
