### ISSUE TITLE
Added pokemon do not have learnsets

### ISSUE THREAD

**Issue by Topyke** [Skeli789/Complete-Fire-Red-Upgrade#121]
Wild pokemon from gens 4 and up have no moves, in HexManiacAdvance it shows them having proper learnsets, I don't know how to fix this issue.

**Comment by Skeli789** [comment]
Remove the commented out movesets in https://github.com/Skeli789/Complete-Fire-Red-Upgrade/blob/master/src/Tables/level_up_learnsets.c
