### ISSUE TITLE
Real time Clock Issues // Graphical Issues

### ISSUE THREAD

**Issue by northx211** [Skeli789/Complete-Fire-Red-Upgrade#122]
Okay so I recently download cfru and it works perfectly beside the weather in overworld... For some reason a lot of animations are glitched... Is there a way to fix the graphical issues / disable the daytime or whatever this is?

![1e](https://github.com/Skeli789/Complete-Fire-Red-Upgrade/assets/170605634/314d23f9-d7ba-4f90-95f9-845bfda78f25)
![3e](https://github.com/Skeli789/Complete-Fire-Red-Upgrade/assets/170605634/301b757a-d125-4dee-8770-28d887d46b41)
![e2](https://github.com/Skeli789/Complete-Fire-Red-Upgrade/assets/170605634/964e9e18-3522-4d48-84a1-357f6bf01fa6)

**Comment by Skeli789** [comment]
Use the `dev` branch https://github.com/Skeli789/Complete-Fire-Red-Upgrade/tree/dev
