### ISSUE TITLE
Compile issue in last version 8/6/2019

### ISSUE THREAD

**Issue by eMMe97** [Skeli789/Complete-Fire-Red-Upgrade#13]
If I compile the last version:

Compiling ./src\build_pokemon.c
./src\build_pokemon.c: In function 'PostProcessTeam':
./src\build_pokemon.c:1782:12: warning: unused variable 'k' [-Wunused-variable]
  u32 i, j, k;

**Comment by Skeli789** [comment]
Should be fixed now
