### ISSUE TITLE
Error: character_customization.c

### ISSUE THREAD

**Issue by eMMe97** [Skeli789/Complete-Fire-Red-Upgrade#14]
New Issue:

Compiling ./src\character_customization.c
In file included from ./src\defines.h:5,
                 from ./src\character_customization.c:1:
./src\character_customization.c: In function 'GetEventObjectGraphicsInfo':
./src\../include/global.h:33:43: warning: division 'sizeof (struct MapObjectGraphicsInfo ***) / sizeof (struct MapObjectGraphicsInfo **)' does not compute the number of array elements [-Wsizeof-pointer-div]
 #define ARRAY_COUNT(array) (sizeof(array) / sizeof((array)[0]))
                                           ^
./src\character_customization.c:143:17: note: in expansion of macro 'ARRAY_COUNT'
  if (tableId >= ARRAY_COUNT(gOverworldTableSwitcher)

**Comment by Skeli789** [comment]
Try now

**Comment by eMMe97** [comment]
Now compiles without errors, but when you get to view an ow the game resets or freeze.

**Comment by Skeli789** [comment]
Are you using the default overworld table switcher from JPAN's engine? If you're not, did you change the pointer at EXISTING_OW_TABLE_ADDRESS in config?

**Comment by eMMe97** [comment]
I don't understand why, but recompiling with // at the ow command and then compiling again by removing  // works without errors ...
