### ISSUE TITLE
Follow me not inserted

### ISSUE THREAD

**Issue by eMMe97** [Skeli789/Complete-Fire-Red-Upgrade#15]
The follow me function is not included in the rom. If I check the hooks I can't find the routines. In fact setting the setvar in the script 0x5005 0x2 the character with id 2 does not follow me. Am I wrong maybe something?

**Comment by LOuroboros** [comment]
If you initialize a Git repository in your CFRU folder and use git grep, there's multiple mentions to a variable called "follower" in the overworld.c file, so I think the functionality is definitely included with this repository.
I do think the explanation on how to use it in the **[CFRU Documentation](https://github.com/Skeli789/Complete-Fire-Red-Upgrade/blob/master/CFRU%20Documentation.docx)** is rather poor though.

I did a quick test, but it was unsuccessful. In theory, **[this script](https://pastebin.com/6C9mn2Rv)** should make it so after interacting with the Person Event No. 9 inside the map, they would instantly start to follow me. Is that correct, @Skeli789?

**Comment by Skeli789** [comment]
The code was there, I just never hooked it in. It's now been fixed up and added officially. See special 0xD1 and special 0xD2 in the documentation for details.
