### ISSUE TITLE
Trainer sending their pokémon in battle twice

### ISSUE THREAD

**Issue by LOuroboros** [Skeli789/Complete-Fire-Red-Upgrade#18]
I found this problem earlier, but I thought it was the result of building a new ROM after doing some changes to config.h and resuming the savefile I already had, so I got a clean version of the repository, built with the default settings and went on to check if the problem still happened. It does.

Context: 2nd Rival Battle in Route 22. I had my Charmander kill Green's Pidgey, and when he sent out his Squirtle, I switched to a low leveled Mankey that was quickly killed by Squirtle in 2 turns with a Tail Whip + Tackle combo.
When I sent out my Charmander afterward, the Player did the action twice for some reason.
https://streamable.com/2p70l

**Comment by Skeli789** [comment]
Thanks for reporting this! This'll be fixed the next time I push.
