### ISSUE TITLE
Cannot use advancemap even if expanded

### ISSUE THREAD

**Issue by Pulceilcane** [Skeli789/Complete-Fire-Red-Upgrade#19]
Hi
not too sure if this is supposed to happen, but when I use an extended Advancemap version I can't use the wild  pokemon section because it shows me badly written moves instead of the expanded list
Maybe I did something worng when I was creating the rom?

also, since I'm already here, how should I use the .ini with G3Hs? Can't I use PGE instead?
Thanks in advance

<img width="960" alt="Annotation 2019-09-24 202019" src="https://user-images.githubusercontent.com/55761493/65538985-d4892180-df08-11e9-83d5-05bd32dca708.png">

**Comment by Skeli789** [comment]
This engine does not add any new Pokemon in. See [here](https://github.com/Skeli789/Dynamic-Pokemon-Expansion) if you want new Pokemon.

Use G3T. It's loads the table pointers directly from the rom so you don't really need to worry about ini files.
