### ISSUE TITLE
2 new compile errors

### ISSUE THREAD

**Issue by eMMe97** [Skeli789/Complete-Fire-Red-Upgrade#20]
### **Error number 1:**

Compiling ./src\character_customization.c
In file included from ./src\defines.h:9,
                 from ./src\character_customization.c:1:
./src\character_customization.c: In function 'GetEventObjectGraphicsId':
./src\../include/global.h:33:43: warning: division 'sizeof (struct MapObjectGraphicsInfo ***) / sizeof (struct MapObjectGraphicsInfo **)' does not compute the number of array elements [-Wsizeof-pointer-div]
 #define ARRAY_COUNT(array) (sizeof(array) / sizeof((array)[0]))
                                           ^
./src\character_customization.c:272:19: note: in expansion of macro 'ARRAY_COUNT'
  if (upperByte >= ARRAY_COUNT(gOverworldTableSwitcher))

### **Error number 2:**

Compiling ./src\overworld.c
./src\overworld.c: In function 'IsRunningDisallowed':
./src\overworld.c:1190:2: error: expected expression before '||' token
  || GetCurrentMapType() == MAP_TYPE_INDOOR

**Comment by Skeli789** [comment]
Fixed.
