### ISSUE TITLE
Special 0xB1 – Choose Item From Bag 

### ISSUE THREAD

**Issue by eMMe97** [Skeli789/Complete-Fire-Red-Upgrade#21]
I set the script this way:

fadescreen 0x1
setvar 0x8000 0x1 @key item pocket
special 0xb1
waitmsg @I also tried to set the command waitstate
compare 0x800e 0xD
if 0x1 goto @ok

however any item I select is taken as right and sends me back to the "ok" part.
This problem did not occur with Shiny Quagsire's routine, even though the script was structured a bit differently. Am I wrong to write the script?

**Comment by Skeli789** [comment]
I'm not seeming to have any problem with it. If you're using an emulator with a memory viewer, can you tell me what you see is being registered in Var800E's memory address (0x203AD30) when you select an item?

**Comment by eMMe97** [comment]
Ok, I solved it! I don't know why but the "compare" does not read higher values ​​than FF. So if I make a 0x800e 0x112, it doesn't respond to the command. In this case I circumvented the problem by setting the value 112 to a different variable (eg setvar 0x8001 0x112) and then I made a comparevars 0x8001 0x800e. Now it works great! Thanks as always for help!
