### ISSUE TITLE
battle_strings.c

### ISSUE THREAD

**Issue by eMMe97** [Skeli789/Complete-Fire-Red-Upgrade#24]
Compiling ./src\battle_strings.c
./src\battle_strings.c: In function 'BattleStringExpandPlaceholders':
./src\battle_strings.c:640:9: warning: unused variable 'class' [-Wunused-variable]
      u8 class = gTrainers[gTrainerBattleOpponent_A].trainerClass;
         ^~~~~
./src\battle_strings.c:795:9: warning: unused variable 'class' [-Wunused-variable]
      u8 class = gTrainers[VarGet(VAR_SECOND_OPPONENT)].trainerClass;

**Comment by Skeli789** [comment]
Fixed.
