### ISSUE TITLE
Error when running make.py

### ISSUE THREAD

**Issue by bluedolphin264** [Skeli789/Complete-Fire-Red-Upgrade#27]
Just trying to run the make.py script to put together the rom gives me this error:

 ./build\01c3c0e0da5d618fdac476b903395938.o: in function `CheckForTrainersWantingBattle':
overworld.c:(.text+0x2c0): undefined reference to `TrainerCanApproachPlayer'

Any help is appreciated :)

**Comment by Skeli789** [comment]
Fixed.
