### ISSUE TITLE
Successful compile, but game is a blank screen

### ISSUE THREAD

**Issue by herrmartell** [Skeli789/Complete-Fire-Red-Upgrade#28]
Hello there. I followed the instructions in here, generated the test.gba file, load it on mGBA but all I'm seeing is a blank screen. I got no errors in the process. What could I be missing? Thanks.

**Comment by LOuroboros** [comment]
Can't replicate. Make sure you're using a v1.0 ROM of Pokémon Fire Red specifically. v1.1 ROMs will not work.
![explorer-2019-12-24_02-26-25](https://user-images.githubusercontent.com/4485172/71395478-db512e80-25f4-11ea-9f24-5572dba8d618.png)
