### ISSUE TITLE
flags?

### ISSUE THREAD

**Issue by roxasth3nobody** [Skeli789/Complete-Fire-Red-Upgrade#31]
hi my first time trying to do this kind of stuff to fire red and i keep running into issues during the CMD step. everytime i do the python scripts//make.py i see something pop up mentioning some flag isnt defined

**Comment by roxasth3nobody** [comment]
./src\daycare.c: In function 'TriggerPendingDaycareEgg':
./src\daycare.c:656:11: error: 'FLAG_PENDING_DAYCARE_EGG' undeclared (first use in this function)
  656 |   FlagSet(FLAG_PENDING_DAYCARE_EGG);
      |           ^~~~~~~~~~~~~~~~~~~~~~~~
./src\daycare.c:656:11: note: each undeclared identifier is reported only once for each function it appears in

things like this. if i could get some help with this, that would be great

**Comment by Skeli789** [comment]
Sorry, that's my bad, it should be working now

**Comment by roxasth3nobody** [comment]
ah thank you. so i just download the new version and all will be fixed?

**Comment by roxasth3nobody** [comment]
./src\overworld.c: In function 'InTanobyRuins':
./src\overworld.c:1729:15: error: 'FLAG_TANOBY_KEY' undeclared (first use in this function); did you mean 'MAPSEC_TANOBY_KEY'?
 1729 |   if (FlagGet(FLAG_TANOBY_KEY))
      |               ^~~~~~~~~~~~~~~
      |               MAPSEC_TANOBY_KEY
./src\overworld.c:1729:15: note: each undeclared identifier is reported only once for each function it appears in

**Comment by Skeli789** [comment]
Should be fixed now too
