### ISSUE TITLE
also a Flag

### ISSUE THREAD

**Issue by Vinteeum** [Skeli789/Complete-Fire-Red-Upgrade#32]
Hello there, new around here, so when doing the python scripts//make.py when it reached the overworld.c I got an error saying FLAG TANOBY KEY undeclared and if I meant 'MAPSEC_TANOBY_KEY,

what shall I do?

Thx for your time!

**Comment by Skeli789** [comment]
Should be fixed now

**Comment by Vinteeum** [comment]
Indeed, no more problems, thank you for your help!

Fast question, does it matter which I do first: complete fire red upgrade or dynamic expansion? (im doing it by this order)

**Comment by Skeli789** [comment]
DPE first. The documenation goes into more detail. Make sure you read it first
