### ISSUE TITLE
strange sound

### ISSUE THREAD

**Issue by roxasth3nobody** [Skeli789/Complete-Fire-Red-Upgrade#34]
so i did all the compiling but now when opening credits open the game makes a horrible screeching

**Comment by roxasth3nobody** [comment]
the test.gba thing doesn't load past the gamefreak black screen credits

**Comment by Skeli789** [comment]
Are you sure you set it up correctly, and did you build it on a ROM that was in progress? I just built it on a fresh FireRed ROM and it works fine.
