### ISSUE TITLE
Very slow walking speed

### ISSUE THREAD

**Issue by Zygoat23** [Skeli789/Complete-Fire-Red-Upgrade#37]
Applying the CFRU has caused the walking speed to slow to a crawl, the DPE is fine though. I'm using the latest commit.

**Comment by Skeli789** [comment]
Is this on a fresh rom, or is your hack already in progress?

**Comment by Zygoat23** [comment]
This is on a rom with only the BW party menu, BW summary screen, Dollsteak’s rombase and DPE + CFRU installed.

**Comment by petuuuhhh** [comment]
getting this issue without bw party menu, bw summary screen, and dollsteak/leon's base

**Comment by LOuroboros** [comment]
A few days ago I tried to build a ROM with both, the DPE and the CFRU. I came across the same problem as well, when I was merging the CFRU in a ROM with the DPE.
https://streamable.com/yxt3c

**Comment by Skeli789** [comment]
Alright. Turns out the old VBA is just a bad emulator (who knew?) and was causing this. I updated some of the code to account for this. This should no longer be an issue

**Comment by Zygoat23** [comment]
Tested with the latest version and it's working fine now.

**Comment by LOuroboros** [comment]
> 
> 
> Alright. Turns out the old VBA is just a bad emulator (who knew?) and was causing this. I updated some of the code to account for this. This should no longer be an issue

That doesn't sound correct. I still had my copy of the repos and the final ROM, and the problem did also show up in mGBA, which is a very accurate GBA Emulator.
https://streamable.com/lpfyfj

I built a new ROM with the latest DPE and the latest CFRU and it certainly doesn't happen anymore though, not on VBA-M SVN r878 nor on mGBA, so there's that.

**Comment by Skeli789** [comment]
Either way, it was an emulator problem (specifically when the RTC was not enabled), and since it's confirmed fixed, this issue is now closed.

**Comment by LOuroboros** [comment]
> 
> 
> Either way, it was an emulator problem (specifically when the RTC was not enabled), and since it's confirmed fixed, this issue is now closed.

That doesn't make sense either. I have it enabled on VBA-M SVN r880, and mGBA's is enabled by default.
It's more likely that the implementation of the RTC that this repository implements was missing something. Even that sounds weird though. Why would that affect the Player Character's walking speed?

But whatever I guess.

**Comment by Skeli789** [comment]
The reason the game was slowing down was because of the Pokerus updates I added in recently. In most emulators I was using, if the RTC was not enabled, the default time in the emulator would be set to some time in 2009. But in VBA, the default time was set to 0, meaning that the game would constantly (every frame) try to update Pokerus in the party since the saved date of the calculation (0) also meant that the calculation had not been done.
