### ISSUE TITLE
Rivalry damage boost is insanely high

### ISSUE THREAD

**Issue by G0LD** [Skeli789/Complete-Fire-Red-Upgrade#38]
I was testing some features and realized a Nidorino with Rivalry as ability was literally KOing anything that breaths with a single Poison Sting. The issue seems to be related to the damage calculation for the ability. Somebody form the discord server helped me to fix it so I opened the issue just in case you cannot read my bug report from the server

**Comment by Skeli789** [comment]
Closing because it's been fixed.
