### ISSUE TITLE
Readme is incomplete

### ISSUE THREAD

**Issue by haven1433** [Skeli789/Complete-Fire-Red-Upgrade#4]
Using this tool is quite a bit more involved than using a patch. It would make sense to include a summary of what a user of this tool gains, so that the user can decide if it's worth the effort. Consider including:

* screenshots of features in use
* main differences added in the battle engine, like the ability to have inverse battles 
* any added data like abilities / moves
* added features like mega evolution

**Comment by Delta456** [comment]
Its currently in development and there are a lot of things to be done first. It will most likely get a release in public when major things are done and there would be a thread made when it will have a beta release.

**Comment by Skeli789** [comment]
As of right now, a temporary documentation can be found in CFRU Documentation.docx. When the engine is ready to be officially released, this file will be replaced with a file called CFRU Documentation.pdf.
