### ISSUE TITLE
Adding More Pokemon boxes (32 Total)

### ISSUE THREAD

**Issue by nathanday5555** [Skeli789/Complete-Fire-Red-Upgrade#40]
i know this isn't much of an issue. more of a question.
how would i go about adding 8 more pc boxes (total 32 instead of 24).
is it as simple as going to  "Complete-Fire-Red-Upgrade/src/pokemon_storage_system.c"

and adding 

#define BOX_25_RAM (BOX_24_RAM + 30)
#define BOX_26_RAM (BOX_25_RAM + 30)
(and obviously  adding the other boxes in the other structs)
and so on
and then compile?

or are there other files i have to edit

EDIT: ok so i did all of that and compiled it. I have 32 boxes now. but the ones i added cant save pokemon, doesnt have a box name, and are full of bad eggs and ?pkmn.

**Comment by Skeli789** [comment]
There is not enough contiguous memory left in the engine to add more boxes at the current moment. Attempting to do so will result in Bad Eggs and non-saveable boxes as you noticed. You can try compressing the Pokemon further, but that will only help you so much.
