### ISSUE TITLE
Constant crashing/restarting on boot screen

### ISSUE THREAD

**Issue by ratquaza** [Skeli789/Complete-Fire-Red-Upgrade#56]
Attempting to run the generated test.gba file on a fresh install on a v1.0 FireRed ROM causes the VisualBoyAdvance emulator to crash and restart on the copyright screen. 
Python 3.7.6 64bit is the only version installed, and devkitPro for GBA development is installed along with the path variable set up.
![image](https://user-images.githubusercontent.com/32216729/85509435-5db8ba80-b639-11ea-98fa-78f511a985e1.png)

**Comment by Skeli789** [comment]
Did you change your insert offset?
