### ISSUE TITLE
Use of decomps

### ISSUE THREAD

**Issue by Rockoria** [Skeli789/Complete-Fire-Red-Upgrade#57]
**Please feel free to remove this if it's the wrong place to discuss a suggestion like this.**

Is there any possibility this will move away from being binary-based and use the pret repo as the default method instead? It's been shiftable for a while and has made a lot of progress. The source for this project is already written in C and could be translated over to fit.

There are lots of interesting and useful features here, but the community has moved away from binary hacking (for good reason) and I don't see why the transition wouldn't be worth the effort.

**Comment by Skeli789** [comment]
Ghoulslash has already ported over many of the CFRU's features to the decomps (see [here](https://www.pokecommunity.com/forumdisplay.php?f=436)). It will take time, but rest assured, eventually the decomps will have an engine as good as this one.
