### ISSUE TITLE
To ask where to put the offsets.ini file

### ISSUE THREAD

**Issue by DarkGyarados218** [Skeli789/Complete-Fire-Red-Upgrade#58]
I did all the steps above, along with using the Dynamic Expansion. I got a test.gba file which was 30 mb or so and an offsets.ini file. I checked all the folders in 3GT and in PGE too, but I can't find where to replace the offsets.ini file.
Please tell me where to place it. 
(I tried renaming it into roms.ini and replacing it in PGE, but it shows an error)

**Comment by Skeli789** [comment]
You don't place it anywhere. It's just there to let you know where things are inserted into the ROM.
