### ISSUE TITLE
It doesn't build right now

### ISSUE THREAD

**Issue by LOuroboros** [Skeli789/Complete-Fire-Red-Upgrade#59]
I'm using the default configuration *(no changes of any kind on my behalf basically)*, everything is set up correctly with Python 3.7.8 installed and its path added to my PATH Environment Variable. I was able to build it normally like 2 days ago at someone's request, in fact, but right now, it's giving me this error:
![cmd-2020-07-24_16-17-52](https://user-images.githubusercontent.com/4485172/88427607-a47d0a00-cdc9-11ea-9643-cff80f08097c.png)

**Comment by Skeli789** [comment]
Should work now

**Comment by LOuroboros** [comment]
Yep, it does build just fine now. Thank you @Skeli789 ^^!
