### ISSUE TITLE
Error Compiling

### ISSUE THREAD

**Issue by UranusDarkness** [Skeli789/Complete-Fire-Red-Upgrade#6]
When I try to compile I get this error

C:\Users\uranu\Desktop\Complete-Fire-Red-Upgrade-master>python scripts//make.py
Traceback (most recent call last):
  File "scripts/build.py", line 286, in <module>
    main()
  File "scripts/build.py", line 270, in main
    linked = link(itertools.chain.from_iterable(objects))
  File "scripts/build.py", line 199, in link
    cmd = [LD] + LDFLAGS + ['-o', linked] + list(objects)
  File "scripts/build.py", line 217, in run_glob
    files = glob(os.path.join(SRC, globstr), recursive = True)
TypeError: glob() got an unexpected keyword argument 'recursive'
Inserting code.
Error: The insertion process could not be completed.
The linker symbol file was not found.

**Comment by Skeli789** [comment]
Please make sure you have Python updated to the latest version. I also added exception handling for this issue in case it happens to anyone in the future.

**Comment by UranusDarkness** [comment]
I have Python 3.7.2 (also added to the Path), but gives me the same error

**Comment by Skeli789** [comment]
Did you have a previous version of python before 3.7.2? If you did, then there may still be remnants of it in your path that needs to be manually removed.

**Comment by UranusDarkness** [comment]
Checked, but I don't know why it gives me the same error

**Comment by UranusDarkness** [comment]
Tried to uninstall all other versions, and now gives an error about DevKitPro's path, which are set like in the documentation

**Comment by UranusDarkness** [comment]
"C:\Complete-Fire-Red-Upgrade>python scripts//make.py
Assembling ./assembly\main.s
Error! The assembler could not be located.
Are you sure you set up your path to devkitPro/devkitARM/bin correctly?
Inserting code.
Error: The insertion process could not be completed.
The linker symbol file was not found."
