### ISSUE TITLE
Make.py error "flag raid battle no forced end"

### ISSUE THREAD

**Issue by Mevalosity** [Skeli789/Complete-Fire-Red-Upgrade#61]
![error code dynamax shields](https://user-images.githubusercontent.com/69146099/89171157-0c2d1500-d581-11ea-83c5-b324f841af53.png)

So this error code keeps popping up, even tough i've unchecked dynamax even being a thing, what can I do about this?

**Comment by Skeli789** [comment]
Yeah, there was a missing conditional compilation flag there. It's been added, so it should work now.
