### ISSUE TITLE
How to decrease the "File Size 3GB" output?

### ISSUE THREAD

**Issue by Gravitium** [Skeli789/Complete-Fire-Red-Upgrade#63]
![image](https://user-images.githubusercontent.com/69876104/90577507-adf46900-e1f3-11ea-8d5f-77b173d646ed.png)

**Comment by Gravitium** [comment]
Problem: the file was named "BPRE0.gba" 
Solution: Renamed the file to "BPRE0"

**Comment by Gravitium** [comment]
![image](https://user-images.githubusercontent.com/69876104/90578994-50fab200-e1f7-11ea-9c21-01a4a5d1af68.png)

**Comment by Gravitium** [comment]
Possible Problem: File Size "2.81 GB"

**Comment by Stevebel** [comment]
For anyone with the large file size issue, I had the same issue and was able to resolve it by using the ["Squirrels"](https://datomatic.no-intro.org/index.php?page=show_record&s=23&n=1616) dump of Fire Red as the base ROM instead of a 1.1 ROM.

**Comment by Gravitium** [comment]
where can I download it from? I am new to this stuff and I don't understand what a squirrels dump is...

**Comment by Delta456** [comment]
@Gravitium You will have to find it yourself. A `Squirrels` is a clean ROM i.e. without any modification. Make sure that you find `Fire Red v1.0 Squirrels` only.
