### ISSUE TITLE
The assembler could not be located.

### ISSUE THREAD

**Issue by ichimo** [Skeli789/Complete-Fire-Red-Upgrade#66]
**Trying to run the python make.py stuff to finish this up and I can't figure out what's wrong from just sifting through files and the paths.  Looking at the other closed issues with the same error didn't help either.  This is the main error.**

![image](https://user-images.githubusercontent.com/17717298/97021919-4d8dea80-1508-11eb-8a1e-be329b12b227.png)

**I have the devkitPro in the PATH variable as well as the 3  variables in the order listed in 1 of the solutions.  I've tried the same process with cmd ran as administrator as well and checked to make sure said assembly file was there which it was.**

![image](https://user-images.githubusercontent.com/17717298/97021173-55995a80-1507-11eb-9968-2efa87724f8e.png)
![image](https://user-images.githubusercontent.com/17717298/97021263-78c40a00-1507-11eb-90b7-b370f83aae2a.png)
![image](https://user-images.githubusercontent.com/17717298/97021326-8c6f7080-1507-11eb-836b-550e41f9c535.png)
![image](https://user-images.githubusercontent.com/17717298/97021451-b3c63d80-1507-11eb-9464-c2c4f2b5d81b.png)

**I installed Python 3.7.9 and it properly opens when typing "python" into cmd.
DevkitPro version is 3.0.3**

**Before you ask, I have tried all of this in my storage drive (E:) as well as my main drive (C:), and yes I did change the paths accordingly.**

//Edit
Forgot to include the related issue link.
https://github.com/Skeli789/Complete-Fire-Red-Upgrade/issues/12

**Comment by Skeli789** [comment]
Try removing the ; in front of the path name, and then restarting your computer.

**Comment by ichimo** [comment]
> Try removing the ; in front of the path name, and then restarting your computer.

I'm happy this worked but am upset that that was the problem since it emphasized it in that other thread.  Thanks dude
