### ISSUE TITLE
'grit' file or directory missing

### ISSUE THREAD

**Issue by CrimsonCrow** [Skeli789/Complete-Fire-Red-Upgrade#77]
get an error when executing `python3.7 scripts/make.py`
```
Compiling Images
There was an error compiling the engine: [Errno 2] No such file or directory: 'grit': 'grit'
```

on linux

**Comment by CrimsonCrow** [comment]
oh nevermind.. it was [this](https://github.com/devkitPro/grit)

this happens when you build devkitpro using their buildscripts

**Comment by aronfoster** [comment]
If you installed devkitpro using their buildscripts, you can still `git clone` the missing tools, `make` them, and export them to your $PATH in order to get this to work.
