### ISSUE TITLE
Possible Download ability bug

### ISSUE THREAD

**Issue by thalescd** [Skeli789/Complete-Fire-Red-Upgrade#83]
In the file "ability_battle_effects.c" at the "case ABILITY_DOWNLOAD" there are two "APPLY_STAT_MOD(opposingDef, &gBattleMons[opposingBank], opposingDef,...". Shouldn't the second one be "APPLY_STAT_MOD(opposingSpDef, &gBattleMons[opposingBank], opposingSpDef,..."?

**Comment by Skeli789** [comment]
You're absolutely right. Can you open a pull request for this problem?

**Comment by thalescd** [comment]
Sure. Just opened it.

**Comment by Skeli789** [comment]
Fixed in #84
