### ISSUE TITLE
Successful build, but ROM crashes after character selection

### ISSUE THREAD

**Issue by msikma** [Skeli789/Complete-Fire-Red-Upgrade#9]
Hi there. I thought I'd give this upgrade a try. My build [seems to go successful](https://gist.github.com/msikma/171d442725d9d40dafc57ee70098523f), but after the character selection it crashes (after Red shrinks to his regular sprite size, the screen stays black and the audio becomes glitched).

My ROMs have the following SHA-1:
```
233478dd1405a699b47f23416aafe7e2e10318ae  test.gba
41cb23d8dccc8ebd7c649cd8fbb58eeace6e2fdc  BPRE0.gba
```

Does anyone know what might have gone wrong?

Caveat: I did have to change some files in the compile script, because I'm on OSX and a couple of things were Windows specific. (I can contribute these back if you are interested. [My changes should be cross-platform](https://github.com/Skeli789/Complete-Fire-Red-Upgrade/compare/master...msikma:master) but I haven't tested it on Windows.)

However I doubt this is the problem, because the changes are mostly just changing slashes in file paths. I had to compile my own grit (v0.8.15) though, since I can't use the .exe file.

Any thoughts are appreciated 🙂

**Comment by Skeli789** [comment]
The python scripts have been updated to support your operating system. Are you able to try now?

**Comment by msikma** [comment]
Thank you for the update! I'll give it a try this weekend.
