### ISSUE TITLE
License and readme contradiction.

### ISSUE THREAD

**Issue by StephenLynx** [Skeli789/Complete-Fire-Red-Upgrade#90]
While you state on your readme that profiting off this project is not allowed, you use a license that does allow people to do exactly that. "0. You just DO WHAT THE FUCK YOU WANT TO.". Also, it is legal to make money off IPs you don't own, fair use does allow you to profit off your work that includes unauthorized use of 3rd party IPs.

To make a point I forked this project and changed it's license to MIT and changed the readme to remove the part about not being able to make money.

https://gitgud.io/stephenlynx/LynxFireRed

✌️

**Comment by Skeli789** [comment]
Thank you for the heads up. It was always supposed to be more of a request, since there's not much I can do if someone actually ignores the statement. That being said, I deleted the license file, so by default the permission to use is given only in the README.
